name: BUILD AND PUSH DOCKER IMAGE
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest 
   steps:
     - name: checkout githu repo 
       uses: actions/checkout@v3 
     - name: login docker 
       uses: docker/login@v3
       with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
     - name: build docker image 
       run: docker build -t aws_image .
     - name: run image 
       run: docker run -d -p 8080:80 aws_image 
     - name: tag image 
       run: docker tag aws_image:latest betrand1997/aws_image:latest
     - name: push image 
       run: docker push betrand1997/aws_image:latest
     - name: check image is running
       run: docker ps 