name: CICD DEPLOY AWS

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install AWS CLI and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          sudo curl -o /usr/local/bin/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
          sudo chmod +x /usr/local/bin/kubectl
          sudo curl -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          sudo chmod +x /usr/local/bin/aws-iam-authenticator

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1

      - name: Print kubeconfig for debugging
        run: |
          echo "Current kubeconfig:"
          cat ~/.kube/config
          echo "Current context:"
          kubectl config current-context
          echo "Context details:"
          kubectl config view -o json

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./kubernetes/namespace.yaml --validate=false
          kubectl apply -f ./kubernetes/deployment.yaml --validate=false
          kubectl apply -f ./kubernetes/service.yaml --validate=false
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
